<?php $helper = Mage::helper('mageinn_priceslider'); ?>
<script type="text/javascript">
//<![CDATA[
function msAjaxCallback()
{
    <?php if($helper->isRwdCallback()): ?>

    /**
     * Uncomment below to enable collapse on "Filter" block in mobile view
     */
    /**
    var toggleElements = $j('.col-left-first .block-layered-nav .block-subtitle--filter, .sidebar:not(.col-left-first) .block .block-title');
    if (window.matchMedia('(max-width: ' + bp.medium + 'px)').matches){
        toggleElements.toggleSingle();
    } else {
        toggleElements.toggleSingle({destruct: true});
    }
     */
   
    // ==============================================
    // UI Pattern - Toggle Content (tabs and accordions in one setup)
    // ==============================================
    
    $j('.toggle-content').each(function () {
        var wrapper = jQuery(this);

        var hasTabs = wrapper.hasClass('tabs');
        var hasAccordion = wrapper.hasClass('accordion');
        var startOpen = wrapper.hasClass('open');

        var dl = wrapper.children('dl:first');
        var dts = dl.children('dt');
        var panes = dl.children('dd');
        var groups = new Array(dts, panes);

        //Create a ul for tabs if necessary.
        if (hasTabs) {
            var ul = jQuery('<ul class="toggle-tabs"></ul>');
            dts.each(function () {
                var dt = jQuery(this);
                var li = jQuery('<li></li>');
                li.html(dt.html());
                ul.append(li);
            });
            ul.insertBefore(dl);
            var lis = ul.children();
            groups.push(lis);
        }

        //Add "last" classes.
        var i;
        for (i = 0; i < groups.length; i++) {
            groups[i].filter(':last').addClass('last');
        }

        function toggleClasses(clickedItem, group) {
            var index = group.index(clickedItem);
            var i;
            for (i = 0; i < groups.length; i++) {
                groups[i].removeClass('current');
                groups[i].eq(index).addClass('current');
            }
        }

        //Toggle on tab (dt) click.
        dts.on('click', function (e) {
            //They clicked the current dt to close it. Restore the wrapper to unclicked state.
            if (jQuery(this).hasClass('current') && wrapper.hasClass('accordion-open')) {
                wrapper.removeClass('accordion-open');
            } else {
                //They're clicking something new. Reflect the explicit user interaction.
                wrapper.addClass('accordion-open');
            }
            toggleClasses(jQuery(this), dts);
        });

        //Toggle on tab (li) click.
        if (hasTabs) {
            lis.on('click', function (e) {
                toggleClasses(jQuery(this), lis);
            });
            //Open the first tab.
            lis.eq(0).trigger('click');
        }

        //Open the first accordion if desired.
        if (startOpen) {
            dts.eq(0).trigger('click');
        }
    });
    
    ConfigurableSwatchesList.init();
    $j(window).trigger('delayed-resize', event);
    
    <?php endif; ?>
        
    // Add your own code here or to System -> Configuration -> Mageinn -> Ajax Price Slider -> Callback JS Code
    <?php echo $this->getChildHtml(); ?>
}
//]]>
</script>